src/binding/util.rs
src/rubysys/util.rs

Removed unnecessary transformation from `str` to `CString` by using `rb_intern2`.

Removed unnecessary memory allocation

---

src/binding/string.rs
src/class/string.rs
src/rubysys/string.rs

I think in most use cases, we wanted to concatenate Rust strings, so I implemented a `&str` API in `src/class/string.rs`. On the other hand, the API in `src/binding/string.rs` is set to `&[u8]` because of a small use case (for example, when concatenating non-UTF-8 character strings).

Implement RString::concat

---

.travis.yml
src/binding/encoding.rs
src/binding/mod.rs
src/binding/string.rs
src/class/encoding.rs
src/class/mod.rs
src/class/string.rs
src/class/traits/encoding_support.rs
src/class/traits/mod.rs
src/class/traits/object.rs
src/lib.rs
src/rubysys/constant.rs
src/rubysys/encoding.rs
src/rubysys/string.rs
src/rubysys/value.rs

Resolves #11 
Works on Ruby 2.5.1 on Linux, Mac, and Windows on both CI services.  For some reason the frozen logic in `force_encoding` is having issues on Ruby 2.4.4 and Ruby 2.3.7.
Locally my system has all three Ruby versions working so this is a bit of a head scratcher :confused: .  I'll try it in Docker and Virtual Machine environments to see if I can replicate the problem.
Works in Docker too.  I left a note in the code about the details.

Preliminary encoding support.

---

src/binding/vm.rs
src/class/vm.rs

[`FnOnce` consumes the variables](https://doc.rust-lang.org/beta/book/second-edition/ch13-01-closures.html#capturing-the-environment-with-closures). In other words, `FnOnce` may contain releasing resources. However, `rb_protect` expects a Ruby exception to occur internally, so it is not good to pass a function containing resource release.
I changed the signature of `vm::protect` from `FnOnce` to `FnMut` and removed heap allocations.
With this pull request and the previous pull request #17, `vm::protect` no longer needs heap allocation. Perhaps #4 may be fixed.

Change `vm::protect` signature

---

examples/eval.rs

I created an example that execute argument string as Ruby script.
```shell
$ cargo build --example eval
$ ./target/debug/examples/eval "puts 'Hello'"
Hello
```
This program is an example and also I'm considering the following usage for testing of build.
```shell
$ cargo clean; cargo run --quiet --example eval 'puts RUBY_VERSION'
2.5.1
$ cargo clean; cargo +1.25.0 run --quiet --example eval 'puts RUBY_VERSION'
2.5.1
$ cargo clean; RUBY=/usr/bin/ruby cargo run --quiet --example eval 'puts RUBY_VERSION'
2.3.3
$ cargo clean; RBENV_VERSION=2.3.7 cargo run --quiet --example eval 'puts RUBY_VERSION'
error: linking with `cc` failed: exit code: 1
...
```

Add an example: eval

---

src/binding/string.rs
src/class/string.rs
src/rubysys/string.rs

1. Fixed test.
2. Revert #27
3. Implement Ruby's `String#length`
I think that it is better to rename `String::new()` to `String::new_usascii_unchecked()`.

Fix string length

---

build.md
src/class/any_object.rs
src/dsl.rs

While moving over from ruru, I ran into a `TypeError` that said some
Ruby method was expecting a `Ruru/MyClassThing` type of object; it was a
bit confusing seeing the "Ruru" part in there, making me think I hadn't
fully cleaned out old artifacts or something.
Also renamed a couple other spots in documentation.

Rename C-class name in dsl wrapper macro

---

CHANGELOG.md
Cargo.toml
README.md
src/binding/string.rs
src/class/string.rs
src/rubysys/string.rs

Windows doesn't have it and apparently some Mac OSes don't.

rb_str_codepoints not available on all OSes

---

README.md

Update README to include instructions to compile ruby with --enable-shared

Update README with --enable-shared instructions

---

src/binding/fixnum.rs
src/binding/hash.rs
src/class/fixnum.rs
src/class/integer.rs
src/rubysys/fixnum.rs

`rb_num2int` can only handle 32bit values
for 64 bit values, we should use `rb_num2long`
For example, if you try to convert ruby Fixnum value  `1125899906842624` to  rust, you'll get:
`RangeError:  1125899906842624 integer too big to convert to `int'`

Use rb_num2long for i64 values

---

src/class/string.rs
src/class/traits/encoding_support.rs

I found that assuming the first item in the comparison, of things that needed to be compared, is a string — isn't quite helpful.

Refactor public API of compatible_encoding

---

src/binding/fixnum.rs
src/binding/hash.rs
src/class/fixnum.rs
src/class/integer.rs
src/lib.rs
src/rubysys/fixnum.rs

This pull request contains several fixes. Please let me know if it is better to split.
* `Integer` type now supports Ruby's `Bignum`
* Rename `num_to_int` to `num_to_i32`. etc.
* It's difficult to understand the type of C. For example, `long` corresponds to `isize` instead of `i64`
* Add test for `Integer`
* It is just to check the behavior of Ruby's implementation.
* Add `LOCK_FOR_TEST` global variable.
* Rust's test works in parallel using threads, but unfortunately it seems that it doesn't work properly if we run Ruby in parallel.

Enhance integer conversions

---

build.rs

I've noticed on Linux that if the symlink for libruby already exists in the `~/.cargo/registry/src/.../rutie/target/release/deps` folder and you rebuild a project with rutie as a dependency you will get the following error:
```
thread 'main' panicked at 'symlink fail: Os { code: 17, kind: AlreadyExists, message: "File exists" }', src/libcore/result.rs:997:5
```
Steps to reproduce:
1) `cargo build` a project with Rutie as a dependency
2) Perform either `cargo clean && cargo build` or update your version of Rust via rustup. 
Unfortunately `cargo clean` doesn't clean the contents of `~/.cargo/registry/src`. As a workaround you can just delete the symlink present in the deps folder. However, this isn't easily achievable when deploying to Heroku. I primarily see this error when a new version …

check if libruby symlink exists before attempting to create one in build script

---

README.md
examples/rutie_ruby_gvl_example/src/lib.rs
examples/rutie_rust_example/Cargo.toml
examples/rutie_rust_example/src/main.rs
src/class/array.rs
src/class/class.rs
src/class/encoding.rs
src/class/enumerator.rs
src/class/rproc.rs
src/class/string.rs
src/class/symbol.rs
src/class/traits/object.rs
src/class/traits/verified_object.rs
src/class/vm.rs
src/dsl.rs
src/util.rs

Remove Option wrapper around arguments that are passed to ruby functions
Instead of passing `None` use `&[]` when no arguments are needed.
~~Since is it not possible to dynamically allocate a slice, we should
allow to pass vectors as arguments that are used to call ruby functions.~~
~~This allows to dynamically define the arguments in rust as vectors.~~
~~Due to the generic type calling those functions with no arguments (`None`)
requires to define the type for `T` even though it is not used.~~
@danielpclark What do you think about changing the signatures to this?
```rust
fn send<T>(&self, method: &str, arguments: &T) -> AnyObject
where
T: AsRef<[AnyObject]>
```
I think `object.send("method", &[])` would write and read nicer than `object.send::<&[AnyObject]>("method", None)`

Remove Option wrapper around arguments that are passed to ruby functions

---

.travis.yml
examples/rutie_ruby_example/Rakefile
examples/rutie_ruby_example/rutie_ruby_example.gemspec
examples/rutie_ruby_gvl_example/Rakefile
examples/rutie_ruby_gvl_example/rutie_ruby_gvl_example.gemspec
examples/rutie_rust_example/Cargo.toml

Users are running in to issues with examples because of old build artifacts so add `cargo clean` to the rake command.  Also have CI test all examples.  And add env for Rust example as is in the README.

preventative action on examples

---

CHANGELOG.md
src/class/vm.rs

The use of `VM::protect` and `VM::eval_str` could really use this feature.

Added VM::error_pop

---

src/binding/hash.rs
src/class/hash.rs
src/rubysys/types.rs
src/types.rs
src/util.rs

`rb_hash_foreach` wants a callback that returns an `st_retval`.
Returning `()` causes (AFAICT?) a read from uninitialized memory, which means who-knows-what happens when iterating. I wasn't able to reduce this to a repeatable test case, but I have been able to observe this happening in real code, and this commit does appear to fix it.
I've hard coded a return of `st_retval::Continue` so as to not break the current API, but maybe `rutie::Hash` should have a new method that allows controlling it.

return st_retval from rb_hash_foreach

---

src/binding/class.rs
src/binding/thread.rs
src/binding/vm.rs
src/class/class.rs
src/class/module.rs
src/class/traits/object.rs
src/util.rs

The warning is "trait objects without an explicit `dyn` are deprecated" and is easily fixed: https://doc.rust-lang.org/edition-guide/rust-2018/trait-system/dyn-trait-for-trait-objects.html

Fix build warnings from bare trait objects

---

CHANGELOG.md
Cargo.toml
README.md
build.rs

Using a cargo feature is a bit easier for projects that never want to link to `libruby` - like those building a ruby extension in rust.

add "no-link" cargo feature

---

src/rubysys/typed_data.rs

Rutie fails to compile on Rust's beta channel because these data types
don't implement Send and Sync.
Signed-off-by: David Calavera <david.calavera@gmail.com>

Implement Send+Sync for rb data types.

---

src/binding/class.rs
src/class/traits/object.rs
src/rubysys/class.rs

Hi there,
I'm just getting my feet wet with Rust/Rutie, so its entirely possible that this patch is nonsensical.  Also, I'm not sure if I have put things in the right place, etc. Happy to make any changes you consider necessary!
The changes are:
- `Object::equals` is now a wrapper around the `rb_equal` C function;
- `Object::is_eql` is now a wrapper around the `rb_eql` C function;
- `Object::is_equal` simply performs an `==` comparison on the underlying values, which is the same behaviour as the `rb_obj_equal` C function.

Add faster versions of `equals`, `is_eql` and `is_equal`

---

README.md
examples/rutie_ruby_example/src/lib.rs
examples/rutie_ruby_gvl_example/src/lib.rs
src/class/class.rs
src/class/module.rs
src/class/rproc.rs
src/class/thread.rs
src/class/traits/object.rs
src/class/traits/verified_object.rs
src/class/vm.rs
src/dsl.rs
src/util.rs

Solve #121 
Change variables' names for better clarity
In methods! macro
itself -> rtself
In Class::new closure
itself -> klass
And, name an ignored param to better clarity
_ -> _rtself

Better names for different `itself` - Issue #121

---

src/class/traits/object.rs
src/class/traits/verified_object.rs

This allows people to use `Option<SOME_VERIFIED_OBJECT>` in method signatures
instead of taking AnyObject and converting.

Make `Option<VerifiedObject>` a `VerifiedObject`

---

src/dsl.rs

This should fix #128 and make rutie warning-free on rust v1.46.

Make generated class!es FFI compatible

---

build.rs
src/dsl.rs

This means that users don't have to add `use lazy_static::lazy_static` or `#[macro_use] extern crate lazy_static` anymore, though they will still have to add the crate as a dependency in their Cargo.toml.

Dont require importing the lazy_static macro

---

src/binding/string.rs

Without this change, Ruby 3.2 was failing to correctly provide me with strings, because the length was always set to zero.
I'm not sure exactly what the change in 3.2 that triggered the problem, but given that rutie's `rstring_len` appears to be an implementation of a function in CRuby that's named `rbimpl_` (which is a namespace meaning "no compatibility should be expected", I don't think this is Ruby's fault.

Use native Ruby function for getting a string's length

---

.github/workflows/ci.yml

Updates the `actions/checkout` action used in the GitHub Actions workflows to its newest major version.
Changes in [actions/checkout](https://github.com/actions/checkout):
> ## v3.5.0
> - Add new public key for known_hosts
>
> ## v3.4.0
> - Upgrade codeql actions to v2
> - Upgrade dependencies
> - Upgrade @actions/io
>
> ## v3.3.0
> - Implement branch list using callbacks from exec function
> - Add in explicit reference to private checkout options
> - Fix comment typos
>
> ## v3.2.0
> - Add GitHub Action to perform release
> - Fix status badge
> - Replace datadog/squid with ubuntu/squid Docker image
> - Wrap pipeline commands for submoduleForeach in quotes
> - Update @actions/io to 1.1.2
> - Upgrading version to 3.2.0
>
> ## v3.1.0
> - Use @actions/core `saveState` and `getState`
> - Add …

Update actions/checkout in GitHub Actions workflow to v3
